import { NodeData } from './types';

export const ROOT_NODE: NodeData = {
  id: 'root',
  title: 'Branevalley Ecosystem',
  imageUrl: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?q=80&w=2070&auto=format&fit=crop',
  description: 'An interactive visualization of the six interconnected ventures of Branevalley.',
  subNodes: [
    {
      id: 'tech',
      title: 'Branevalley Technologies',
      description: 'Pioneering the future of technology, with a special focus on FinTech innovations.',
      imageUrl: 'https://images.unsplash.com/photo-1518770660439-4636190af475?q=80&w=2070&auto=format&fit=crop',
      subNodes: [
        { 
          id: 'finance', 
          title: 'Finance',
          description: 'Revolutionizing financial services with cutting-edge technology.',
          imageUrl: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?q=80&w=1911&auto=format&fit=crop',
          subNodes: [
            { id: 'fintech_platforms', title: 'Fintech Platforms' },
            { id: 'blockchain', title: 'Blockchain Solutions' },
            { id: 'payment_gateways', title: 'Payment Gateways' },
            { id: 'robo_advisors', title: 'Robo-Advisors' },
            { id: 'insurtech', title: 'Insurtech' },
            { id: 'regtech', title: 'Regtech' },
          ]
        },
        { 
          id: 'education', 
          title: 'Education',
          description: 'Transforming learning with interactive and accessible EdTech solutions.',
          imageUrl: 'https://images.unsplash.com/photo-1523240795612-9a054b0db644?q=80&w=2070&auto=format&fit=crop',
          subNodes: [
            { id: 'e_learning', title: 'E-Learning Platforms' },
            { id: 'virtual_labs', title: 'Virtual Labs' },
            { id: 'student_info_systems', title: 'Student Info Systems' },
            { id: 'ai_tutoring', title: 'AI Tutoring' },
            { id: 'online_courses', title: 'Online Courses' },
            { id: 'ed_games', title: 'Educational Games' },
          ]
        },
        { 
          id: 'transport', 
          title: 'Transport',
          description: 'Innovating mobility with smart logistics and transportation systems.',
          imageUrl: 'https://images.unsplash.com/photo-1570125909232-eb263c187f0e?q=80&w=2072&auto=format&fit=crop',
          subNodes: [
            { id: 'logistics_software', title: 'Logistics Software' },
            { id: 'fleet_management', title: 'Fleet Management' },
            { id: 'ride_sharing', title: 'Ride-Sharing Apps' },
            { id: 'smart_parking', title: 'Smart Parking' },
            { id: 'ev_charging', title: 'EV Charging Networks' },
            { id: 'traffic_management', title: 'Traffic Management' },
          ]
        },
        { 
          id: 'technology', 
          title: 'Technology',
          description: 'Developing core technologies that power future innovations.',
          imageUrl: 'https://images.unsplash.com/photo-1488590528505-98d2b5aba04b?q=80&w=2070&auto=format&fit=crop',
          subNodes: [
            { id: 'ai_ml', title: 'AI & Machine Learning' },
            { id: 'iot', title: 'Internet of Things' },
            { id: 'cloud_computing', title: 'Cloud Computing' },
            { id: 'cybersecurity', title: 'Cybersecurity' },
            { id: 'big_data', title: 'Big Data Analytics' },
            { id: 'robotics', title: 'Robotics' },
          ]
        },
        { 
          id: 'real_estate', 
          title: 'Real Estate',
          description: 'Streamlining the property market with innovative PropTech solutions.',
          imageUrl: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=2070&auto=format&fit=crop',
          subNodes: [
            { id: 'property_portals', title: 'Property Portals' },
            { id: 'virtual_tours', title: '3D Virtual Tours' },
            { id: 'smart_contracts', title: 'Smart Contracts' },
            { id: 'property_management', title: 'Property Management SaaS' },
            { id: 'iot_homes', title: 'IoT Smart Homes' },
            { id: 'real_estate_analytics', title: 'Analytics Platforms' },
          ]
        },
        { 
          id: 'hospitality', 
          title: 'Hospitality',
          description: 'Enhancing the guest experience with modern hospitality technology.',
          imageUrl: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?q=80&w=2070&auto=format&fit=crop',
          subNodes: [
            { id: 'booking_engines', title: 'Booking Engines' },
            { id: 'pms', title: 'Property Management Systems' },
            { id: 'contactless_checkin', title: 'Contactless Check-in' },
            { id: 'guest_apps', title: 'Guest Experience Apps' },
            { id: 'revenue_management', title: 'Revenue Management' },
            { id: 'smart_rooms', title: 'Smart Room Tech' },
          ]
        },
      ],
    },
    {
      id: 'shop',
      title: 'Branevalley Shop',
      description: 'Your one-stop destination for high-performance gaming gear and computer gadgets.',
      imageUrl: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?q=80&w=2070&auto=format&fit=crop',
      subNodes: [
        { 
          id: 'laptops', 
          title: 'Laptops',
          description: 'High-performance laptops for gaming, creation, and work.',
          imageUrl: 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?q=80&w=2071&auto=format&fit=crop',
          subNodes: [
            { id: 'gaming_laptops', title: 'Gaming Laptops' },
            { id: 'ultrabooks', title: 'Ultrabooks' },
            { id: 'macbooks', title: 'Macbooks' },
            { id: 'workstations', title: 'Mobile Workstations' },
            { id: 'chromebooks', title: 'Chromebooks' },
            { id: '2_in_1', title: '2-in-1 Convertibles' },
          ]
        },
        { 
          id: 'gaming', 
          title: 'Gaming',
          description: 'Consoles, peripherals, and accessories for the ultimate gaming experience.',
          imageUrl: 'https://images.unsplash.com/photo-1603481588273-2f908a9a7a1b?q=80&w=2070&auto=format&fit=crop',
          subNodes: [
            { id: 'ps5', title: 'PS5' },
            { id: 'ps4', title: 'PS4' },
            { id: 'server', title: 'Gaming Servers' },
            { id: 'curved_screen', title: 'Curved Screens' },
            { id: 'gaming_chairs', title: 'Gaming Chairs' },
            { id: 'headsets', title: 'Headsets' },
          ]
        },
        { 
          id: 'drones', 
          title: 'Drones',
          description: 'Capture stunning aerial footage with our range of consumer and professional drones.',
          imageUrl: 'https://images.unsplash.com/photo-1527977966376-1c8408f9f108?q=80&w=1965&auto=format&fit=crop',
          subNodes: [
            { id: 'drone_black', title: 'Drone Black' },
            { id: 'dji', title: 'DJI Series' },
            { id: 'chunu', title: 'Chunu Models' },
            { id: 'fpv', title: 'FPV Racing Drones' },
            { id: 'camera_drones', title: 'Camera Drones' },
            { id: 'mini_drones', title: 'Mini Drones' },
          ]
        },
        { 
          id: 'vr_headsets', 
          title: 'VR Headsets',
          description: 'Immerse yourself in virtual worlds with cutting-edge VR technology.',
          imageUrl: 'https://images.unsplash.com/photo-1544415347-971a74a1239c?q=80&w=2070&auto=format&fit=crop',
          subNodes: [
            { id: 'meta_quest', title: 'Meta Quest' },
            { id: 'valve_index', title: 'Valve Index' },
            { id: 'htc_vive', title: 'HTC Vive' },
            { id: 'psvr', title: 'PlayStation VR' },
            { id: 'standalone', title: 'Standalone VR' },
            { id: 'pc_vr', title: 'PC-Powered VR' },
          ]
        },
        { 
          id: 'graphics_design', 
          title: 'Graphics Design',
          description: 'Comprehensive creative services, from branding and print to digital marketing and 3D visuals.',
          imageUrl: 'https://images.unsplash.com/photo-1626785774573-4b799315345d?q=80&w=2071&auto=format&fit=crop',
          subNodes: [
            { id: 'posters', title: 'Posters' },
            { id: 'social_media_marketing', title: 'Social Media Marketing' },
            { id: 'stickers', title: 'Stickers' },
            { id: 'printing', title: 'Printing' },
            { id: 'tshirt_printing', title: 'T-Shirt Printing' },
            { id: 'car_wrapping', title: 'Car Wrapping' },
            { id: 'camcode', title: 'Camcode' },
            { id: '3d_visuals', title: '3D Visuals' },
            { id: 'media', title: 'Media' },
            { id: 'marketing', title: 'Marketing' },
            { id: 'web_design', title: 'Web Design' },
            { id: 'apps', title: 'Apps' },
            { id: 'ads', title: 'Ads' },
            { id: 'google_search', title: 'Google Search' },
            { id: 'videography', title: 'Videography' },
            { id: 'photography', title: 'Photography' },
          ]
        },
        { 
          id: 'accessories', 
          title: 'Accessories',
          description: 'A wide range of essential tech accessories, from power banks and cables to professional audio and security systems.',
          imageUrl: 'https://storage.googleapis.com/aistudio-hosting/9a83a0a3-a00d-4581-807c-9b78a9c8f00f.png',
          subNodes: [
            { id: 'power_banks', title: 'Power Banks' },
            { id: 'monitors', title: 'Monitors' },
            { id: 'tablets', title: 'Tablets' },
            { id: 'printers', title: 'Printers' },
            { id: 'laptops_acc', title: 'Laptops' },
            { id: 'cctvs', title: 'CCTVs' },
            { id: 'routers', title: 'Routers' },
            { id: 'biometric', title: 'Biometric' },
            { id: 'camcord', title: 'Camcorders' },
            { id: 'vr_acc', title: 'VR' },
            { id: 'drones_acc', title: 'Drones' },
            { id: 'cables', title: 'Cables' },
            { id: 'ps5_acc', title: 'PS5' },
            { id: 'tvs_acc', title: 'TVs' },
            { id: 'starlink_acc', title: 'Starlink' },
            { id: 'advertising_screens', title: 'Advertising Screens' },
            { id: 'all_in_one', title: 'All In One PCs' },
            { id: 'cpu', title: 'CPU' },
            { id: 'servers', title: 'Servers' },
            { id: 'extenders', title: 'Extenders' },
            { id: 'smartphones', title: 'Smartphones' },
            { id: 'pos', title: 'POS' },
            { id: 'adapters', title: 'Adapters' },
            { id: 'headphones', title: 'Headphones' },
            { id: '3d_glasses', title: '3D Glasses' },
            { id: 'access_control', title: 'Access Control' },
            { id: 'alarm_trackers', title: 'Alarm Trackers' },
            { id: 'scanners', title: 'Scanners' },
            { id: 'audio', title: 'Audio' },
            { id: 'hosting', title: 'Hosting' },
            { id: 'dj_tools', title: 'DJ Tools' },
          ]
        },
      ],
    },
    {
      id: '360',
      title: 'Brane360',
      description: 'Providing robust software-as-a-service solutions, including accounting and cybersecurity.',
      imageUrl: 'https://images.unsplash.com/photo-1544197150-b99a580bb7a8?q=80&w=2070&auto=format&fit=crop',
      subNodes: [
        { id: 'accounting', title: 'Accounting Suite' },
        { id: 'cybersecurity', title: 'Cybersecurity' },
        { id: 'crm', title: 'CRM Platform' },
        { id: 'cloud', title: 'Cloud Solutions' },
        { id: 'hr', title: 'HR Software' },
        { id: 'pm', title: 'Project Mgmt' },
      ],
    },
    {
      id: 'motorspot',
      title: 'Motorspot Kilimani',
      description: 'Redefining car dealerships and exploring the future of personal and space travel.',
      imageUrl: 'https://images.unsplash.com/photo-1614729569213-9c4792626094?q=80&w=1974&auto=format&fit=crop',
      subNodes: [
        { id: 'ev', title: 'EV Showroom' },
        { id: 'imports', title: 'Luxury Imports' },
        { id: 'space', title: 'Space Tourism' },
        { id: 'aero', title: 'Aero-Engineering' },
        { id: 'mods', title: 'Custom Mods' },
        { id: 'service', title: 'Service Center' },
      ],
    },
    {
      id: 'mothership',
      title: 'Mothership',
      description: 'Empowering communities through innovative microfinance and financial services.',
      imageUrl: 'https://images.unsplash.com/photo-1531545514256-b1400bc00f31?q=80&w=1974&auto=format&fit=crop',
      subNodes: [
        { id: 'loans', title: 'Startup Loans' },
        { id: 'p2p', title: 'P2P Lending' },
        { id: 'invest', title: 'Investment Hub' },
        { id: 'mobile_banking', title: 'Mobile Banking' },
        { id: 'insuretech', title: 'InsureTech' },
        { id: 'finlit', title: 'Financial Literacy' },
      ],
    },
    {
      id: 'treenity',
      title: 'Treenity',
      description: 'Building the next generation of real estate with a focus on sustainable and smart housing.',
      imageUrl: 'https://images.unsplash.com/photo-1617103995440-a68c4a451432?q=80&w=1974&auto=format&fit=crop',
      subNodes: [
        { id: 'smart_homes', title: 'Smart Homes' },
        { id: 'eco_villages', title: 'Eco-Villages' },
        { id: 'urban_living', title: 'Urban Living' },
        { id: 'modular', title: 'Modular Housing' },
        { id: 'virtual_tours', title: 'Virtual Tours' },
        { id: 'prop_mgmt', title: 'Property Mgmt' },
      ],
    },
  ]
};